### ISSUE TITLE
Environment Breakout

### ISSUE THREAD

**Issue by AHermanAdsystech** [Adsystech/MCLink#62]

**Comment by clopez720** [comment]
Environment breakout has already been emailed to you @AHermanAdsystech

**Comment by AHermanAdsystech** [comment]
Did I reassign you this mistakenly?


On Jan 27, 2015, at 11:48 AM, Charlie <notifications@github.com<mailto:notifications@github.com>> wrote:


Environment breakout has already been emailed to you @AHermanAdsystech<https://github.com/AHermanAdsystech>

**Comment by clopez720** [comment]
I believe so. @AHermanAdsystech
